### ISSUE TITLE
IronSendMotion broken on Mac OS X

### ISSUE THREAD

**Issue by alexhbnr** [Vigemus/iron.nvim#101]
When using iron.nvim on a Mac OS X system, I have a similar problem as described here: https://github.com/Vigemus/iron.nvim/pull/85#issuecomment-412952997

I tried both using the Python-based 

`autocmd Filetype python nmap <buffer> \l <Plug>(iron-send-motion)`

as well as the lua-based

`autocmd Filetype python nmap <buffer> \l :lua require("iron").core.send_motion("line")<CR>`

way of sending code to my Python REPL. In both cases, it sends incomplete text to the REPL. Using the exact same mappings on a Linux machine works fine.

Later in the same thread, it was stated that the escape characters might be the issue and it should be fixed (https://github.com/Vigemus/iron.nvim/pull/85#issuecomment-416865046). I am testing the newest commit and still have the same issues.

Is there any update on this?

**Comment by hkupty** [comment]
It's really difficult for me to test this on OS X as I only have a linux laptop.

Is it still happening? Maybe it was a neovim->terminal issue.

Nonetheless, I'm really sorry for not following-up in for such a long time.
Lately it's been really hard for me to keep up w/ my open source projects, so I'm taking a look at everything whenever I can.

**Comment by alexhbnr** [comment]
Hi @hkupty,
I am sorry, I took me a while to come back to you. The good news is that it now works when I either use `require("iron").core.send_line()` to send a line or `require("iron").core.visual_send()` to send the current selected text over. `require("iron").core.send_motion("visual")` doesn't work though, but send the whole file to the REPL.

However, after spending some time digging through the lua code of iron.nvim, I think I can get work for me. I think the project would benefit from some additional documentation, e.g. a small tutorial with some explanations, that is available outside of NeoVim directly on the GitHub page, too.

I know it takes a lot of time and effort to keep these side projects running, so your effort is highly appreciated! Thank you very much.
