### ISSUE TITLE
Colors not showing on ipython REPL

### ISSUE THREAD

**Issue by xuesoso** [Vigemus/iron.nvim#105]
Hi, thanks for the wonderful plugin! One issue I have is, it seems the colors for syntax do not show in the ipython REPL started by iron nvim. Colors / syntax do show, however, when one starts a terminal and call ipython from inside nvim. Would you have any recommendation for adding in this configuration? Thanks! Attached are screenshots of examples.
![screenshot_2019-02-11_22-49-44](https://user-images.githubusercontent.com/15006047/52617116-9ba3ad00-2e4f-11e9-88b6-dc0ad2d147d7.png)

**Comment by hkupty** [comment]
It seems by default it's spawning `python` instead. 

When I spawn an `ipython` repl, the buffer name is `term://.//20205:ipython`.

So *probably* I'm doing a poor job trying to find the actual executable and I'm missing ipython when trying to pick the repl, falling back to `python` executable.

**Comment by hkupty** [comment]
I'll investigate this further, but meanwhile, you can try doing `:term ipython` to see if vim actually finds it. I'm using vim's mechanisms to find the executable, so if this runs, the issue might be somewhere else.

Another alternative would be to explicitly configure iron to use `ipython`:

```viml
" On your init.vim

lua << EOF
require('iron').core.set_config{
  preferred = {
    python = "ipython"
  }}
EOF
```

**Comment by xuesoso** [comment]
You are right. It seems iron wasn't executing ipython. Adding in the config lines below in "init.vim" solves the issue.

lua << EOF
require('iron').core.set_config{
  preferred = {
    python = "ipython"
  }}
EOF

**Comment by hkupty** [comment]
Glad to know it was solved!

Thanks for the issue and I'm glad you're having a good experience with iron.nvim.

Please don't refrain to open another issue if you have any other problems.

Best,
Henry
