### ISSUE TITLE
scala single line unnecessary :pate & interpreting

### ISSUE THREAD

**Issue by yelled1** [Vigemus/iron.nvim#110]
I am a bit bothered by this, but not a show stopper.
When I send a single line on Scala.
via:
autocmd Filetype scala nmap <localleader>\ :call luaeval('require("iron").core.send(_A[1],_A[2])', [&ft, getline('.')])<CR>

line is = ```    val sr = Set( 1 to 5 ) // Set[Range.Inclusive] = Set(Range.Inclusive(1,2, 3, 4, 5))```

I get following verbose interaction on the terminal
```
scala> :paste
// Entering paste mode (ctrl-D to finish)

    val sr = Set( 1 to 5 ) // Set[Range.Inclusive] = Set(Range.Inclusive(1,2, 3, 4, 5))

// Exiting paste mode, now interpreting.
sr: scala.collection.immutable.Set[scala.collection.immutable.Range.Inclusive] = Set(Range(1, 2, 3, 4, 5))
scala>
```
The ```:paste ... // Exiting paste mode, now interpreting.``` seems unnecessary for a single line sending. 
This should be reserved for multiline.
Python repl does not do this & look clean.
Thanks much,

**Comment by hkupty** [comment]
Hi, thanks for the issue.

I'll check this. It should be simple to fix for single line.

Cheers

**Comment by yelled1** [comment]
Would really be great!
Apologies about bother u about the darn software (apt) problem. I would have never guessed until I dug in deeper.
Thank you,

**Comment by hkupty** [comment]
I'm really sorry for not looking at this before. It should be fixed by the commit above.
I'm trying to burn down all the issues on my projects now, so hopefully this is still relevant.

Best regards,
Henry.

**Comment by hkupty** [comment]
The commit was reverted as it caused #127. I'll approach this with another solution, more specific for scala.
