### ISSUE TITLE
Can we add a new mapping: <Plug>(iron-send-line)?

### ISSUE THREAD

**Issue by randomizedthinking** [Vigemus/iron.nvim#111]
Can we add a send-line command in iron.nvim given it is so frequently used? The mapping `<localleader>sl` for scala would be a good default one to use.

Assuming it is not hard, if you can provide some heads up, I'd happy to have the implementation.

**Comment by randomizedthinking** [comment]
Here is a PR for this simple function: #112... thx!

**Comment by hkupty** [comment]
Hi, thanks a lot for the issue and the PR.

I've been a bit away from iron recently due to some personal issues. This is a great way of keeping the project alive and well.

Thanks!
