### ISSUE TITLE
vsplit doesn't split evenly

### ISSUE THREAD

**Issue by danjenson** [Vigemus/iron.nvim#118]
Recently when I call :IronRepl (Fedora 29, recent iron vim pull, nvim 0.3.3), the repl opened no longer splits the screen and is much wider, pushing my code to wrap around 70 chars on the right.

**Comment by randomizedthinking** [comment]
Not sure how big your screen is. The default width of an iron repl is 100. You can change the setting based on your screen size. For instance,

```vim
lua << EOF
local iron = require('iron')

iron.core.set_config {
  repl_open_cmd = "topleft vertical 80 split",
}
EOF
```

**Comment by danjenson** [comment]
it used to just use the default vsplit, which split it in half -- is there any way to do that?

**Comment by randomizedthinking** [comment]
You can try the following in your `init.vim`.

```vim
lua << EOF
local iron = require('iron')

iron.core.set_config {
  repl_open_cmd = "topleft vertical split",
}
EOF
```

**Comment by danjenson** [comment]
That works for the first split, but it doesn't automatically resize as you open new vim windows. Previously, it seems like it allowed vim to manage the width, now it's fixed from the time it's created. Frequently, I'll open 4 panels on my screen, repl on the left, and 3 code editors on the right, and previously they would all adjust to be 1/4 the screen width. Now IronRepl is half the screen on the left and the remaining 3 divide the right. It's possible to recreated this by changing when I create the repl but it seems janky to do that. Is there any way to revert to the old behavior?

**Comment by randomizedthinking** [comment]
It is possible. A quick and dirty solution is to add the following line in `init.vim`.

```vim
autocmd BufLeave * if &buftype == 'terminal' | :set nowfw | endif
```

**Comment by danjenson** [comment]
fixed
