### ISSUE TITLE
IPython AutoIndent

### ISSUE THREAD

**Issue by mwcm** [Vigemus/iron.nvim#122]
This is more to do with IPython than Iron, but I thought it might help anyone who was encountering the same thing...

Kept receiving an `Unexpected Indent` Indentation Error on using `iron-send-motion` in visual mode.

Issue ended up being that IPython was trying to autoindent the lines from vim that were already indented properly, so if i sent the lines with all of my indentation removed, the code would execute properly.

Solution was to add `--no-autoindent` to`plugins.lua` so now it looks like below. Code sends and executes correctly now without removing indentation in Nvim.
```
local iron = require('iron')

iron.core.add_repl_definitions {
  python = {
    venv_python = {
      command = "/Users/mwcmitchell/.virtualenvs/ipython/bin/ipython3 --no-autoindent"
    }
  }
}

iron.core.set_config {
  preferred = {
    python = "venv_python",
  }
}
```

**Comment by hkupty** [comment]
Hi,

Thanks for the issue and the fix. I believe that's a good default and I could add that to iron, so everyone benefits from it.

Best,
Henry

**Comment by hkupty** [comment]
I just pushed a branch(`fix/ipython-no-autoindent`) containing the default. If possible, could you test it for me?

Thanks a lot.

**Comment by mwcm** [comment]
Hey thank you for the update 😄 
Sorry I'm just seeing this, I'll test it out as soon as I'm home from work!

**Comment by mwcm** [comment]
Just removed my `--no-autoindent` and pulled the branch, works perfectly.
Thanks again Henry!

**Comment by hkupty** [comment]
Amazing! I'll merge it!

Thanks for the issue and for testing the fix.

Best regards,
Henry

**Comment by randomizedthinking** [comment]
This is a neovim issue that bracket paste is not currently supported in the terminal buffer.

**Comment by wty20060888** [comment]
@hkupty `ipython --no-autoindent` works fine, but  in `jupyter console` , the indentation problem is still not solvable.
