### ISSUE TITLE
repl command not executed for single line paste

### ISSUE THREAD

**Issue by doubleloop** [Vigemus/iron.nvim#127]
The problem was introduced by 7a86d086dd38aa14856f357d5b5452d2c53b7c70. I can observe it in python and ipython.

Steps to reproduce:
```
$ cat testrc.vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'BurningEther/iron.nvim',      { 'do': ':UpdateRemotePlugins' }
call plug#end()

nmap <F5> 0ctr$
vmap <buffer> <F5> <Plug>(iron-send-motion)
$ cat test.py
print('test')
$ nvim -u testrc.vim test.py
```
* run IronRepl 
* insert the line of code using `<F5>` twice
* alternative: insert the line of code using `V<F5>` twice

Before 7a86d086dd38aa14856f357d5b5452d2c53b7c70:
```
 Python 2.7.16+ (default, Jul  8 2019, 09:45:29)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print('test')
test
>>>
>>> print('test')
test
>>>
>>>
```

After 7a86d086dd38aa14856f357d5b5452d2c53b7c70:
```
Python 2.7.16+ (default, Jul  8 2019, 09:45:29)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print('test')print('test')
```

NVIM v0.4.0-1792-gc6eb1f42b

**Comment by hkupty** [comment]
Hi, thank you very much for the issue.

I just came up with a fix for it, which on my local tests appear to work.

Do you mind testing #128 before I proceed?

Best regards,
Henry

**Comment by doubleloop** [comment]
I've just tested #128 and it works as expected :) Thank you for the fix

**Comment by doubleloop** [comment]
I also observed that there is unnecessary end of line in ipython repl after paste so I proposed #129 for this:

Before:
```
[ins] In [1]: print('test')
         ...:
test

[ins] In [2]:
```

After:
```
[nav] In [1]: print('test')
test

[ins] In [2]:
```

**Comment by hkupty** [comment]
Thanks for testing my branch. I've just incorporated your change into my branch. I really appreciate your effort :)

I'm fixing the tests for the branch now and I'll merge asap.

Best regards,
Henry
