### ISSUE TITLE
Update REPL command for Elm

### ISSUE THREAD

**Issue by dlukes** [Vigemus/iron.nvim#142]
`elm-repl` has become a subcommand of the `elm` command, so I think that `lua/iron/fts/elm.lua` should be updated to the following:

```lua
elm.elm = {
  command = {"elm", "repl"},
}

return elm
```

Tested it and it seems to be working :)

**Comment by hkupty** [comment]
Sorry for taking long to answer your issue. Life has got in the way for the last couple of weeks.

Hope the last commit fixes it for you. Please let me know if it doesn't.

Best regards and happy holidays,
Henry Kupty

**Comment by dlukes** [comment]
No worries, on the contrary, thank you very much for making time to take a look at this :) Happy holidays to you too!
