### ISSUE TITLE
Disable mappings

### ISSUE THREAD

**Issue by urbainvaes** [Vigemus/iron.nvim#144]
Hi Henry!

Is it possible to disable the default mappings?

By default, `iron.nvim` maps `cl` to `<Plug>(iron-clear)`, but I use the default `cl` in place of `s` (because `s` is mapped by `vim-sneak`). I tried setting `let g:iron_map_defaults=0` but it didn't solve the problem.

Thank you very much!

**Comment by rafi** [comment]
You need to disable also the "extended" mapping option:
```viml
let g:iron_map_defaults = 0
let g:iron_map_extended = 0
```

**Comment by urbainvaes** [comment]
Thanks, that worked!
