### ISSUE TITLE
Missing linefeed --> Visualmode

### ISSUE THREAD

**Issue by Ikariux** [Vigemus/iron.nvim#146]
When using visual_send() all lines are concatenated without a linefeed, which leeds to syntax/indent errors in python.

Setup: NVim on Windows, Python 3.x 
Since I am completely new to Vimscript and Lua I might have overseen something, but changing 
`table.insert(tbl, i)` into `table.insert(tbl, i .. "\13")` in tables.lua --> fns.extend fixed this issue for me.

Btw. thanks for this plugin!

**Comment by yelled1** [comment]
Pls approve pull soon. Same issue on Win visual.
Thanks you!
