### ISSUE TITLE
How to support go?

### ISSUE THREAD

**Issue by glepnir** [Vigemus/iron.nvim#154]
I use [gore](https://github.com/motemen/gore) to repl, i set this, but didn't work.
```lua
local iron = require('iron')

iron.core.add_repl_definitions {
  go = {
    mycustom = {
      command = {"gore"}
    }
  }
}

iron.core.set_config {
  preferred = {
    go = "gore",
    python = "ipython",
    typescript = "ts-node",
    javascript = "node"
  }
}
```
open a go file ,then run repl , nothing happed.

**Comment by hkupty** [comment]
Hi, thanks for the issue.

You almost got it right, on the preferred configuration, you have to add the name of the definition you just added above, in your case `mycustom`. That's what's going to be used to retrieve the repl configuration.

Best regards,
Henry

**Comment by taigacute** [comment]
@hkupty  so what should i do? i don't write lua . thanks for your reply.

**Comment by hkupty** [comment]
No worries. If you change your definitions to have the key named `gore`, it should work:
```lua
iron.core.add_repl_definitions {
  go = {
    gore = {
      command = {"gore"}
    }
  }
}
```

**Comment by taigacute** [comment]
@hkupty  Fine, i got it work, But the repl window is very strange, the repl window is very large, it should be half the size,It seems that providing an option to set the position and size of the window is a good way.
![image](https://user-images.githubusercontent.com/41671631/78554920-9a48f700-783e-11ea-9826-965770d2138c.png)

**Comment by glepnir** [comment]
@hkupty  Hi,any update for window?

**Comment by hkupty** [comment]
Sorry I missed this issue. I don't mean to make things stalled, but life has been very busy and I'm unfortunately unable to give the proper attention to the project.

Iron exposes it's configuration through a lua variable that can be set like this:
```lua
iron.core.set_config {
    repl_open_cmd = "topleft vertical 50 split"
}
```

The default value is `  repl_open_cmd = "topleft vertical 100 split"`.

Once again, I'm really sorry I lost track of this issue.

Best regards,
Henry

**Comment by glepnir** [comment]
Don't worry, I've solved it recently, everything works fine
![image](https://user-images.githubusercontent.com/41671631/82644244-91bc4c80-9c43-11ea-80b6-fd97baf38150.png)

**Comment by hkupty** [comment]
Glad to know :)

**Comment by qadzek** [comment]
For future reference: [yaegi](https://github.com/traefik/yaegi) works pretty well with `iron.nvim` for me:

```lua
repl_definition = {
  go = {
    command = { "yaegi" },
  },
}
```
