### ISSUE TITLE
Sending splits statements

### ISSUE THREAD

**Issue by jakubkaczor** [Vigemus/iron.nvim#327]
When I send the text to the buffer, the statements are executed as if I put them in the REPL one by one, pressing enter on each line, but the expected behavior is to execute the entire code chunk at once. The code to be send is
```julia
"Solve the system in the form of ``AX = B``"
function solve_precisely(A, B)
   A \ B
end
```

It is executed as follows.

![image](https://user-images.githubusercontent.com/57760986/229289790-65d915b6-38e6-4c46-9b72-a5cf41cb84e3.png)

At first, I send the text to the REPL, so the given string is input as a statement, then a function definition is input as another statement. I would like it to work as the second time, obtained by copying the text, pasting it to the buffer with the REPL and then pressing enter. In the first case, the string can't be interpreted as a docstring, therefore `?solve_precisely` doesn't show any documentation.

Additionally, you can see the indentation problems in the first approach, but this is not the topic of this issue.

**Comment by hkupty** [comment]
I'm sorry for taking long to respond - this somehow got lost in my notifications.

I'm not sure about julia as I don't know much about it, but I would assume it does allow for bracketed paste. 

In your config, you can try adding the following:
```lua
require("iron").setup {
  config = {
    -- your config
    repl_definition = {
      julia = {
        command = {"julia"},
        format = require("iron.fts.common").bracketed_paste
      }
    }
  }
}
```

If that works, I can probably add it as a default to the julia repl.

Best regards,
Henry

**Comment by jakubkaczor** [comment]
I tested the snippet you provided for the snippet I had originally given, and it appeared to work. Thank you!
