### ISSUE TITLE
Feature request: 1 REPL per filetype

### ISSUE THREAD

**Issue by alok** [Vigemus/iron.nvim#35]
[vimcmdline](https://github.com/jalvesaq/vimcmdline/commit/5b9c2cbba48c3d9e19019d6af39872c7a8f9a908) added support for this a while ago, and it's handy.  All files of a given filetype share a REPL, and different filetypes have their own REPLs linked to them.

You could probably use a dictionary mapping filetypes to jobids to implement that, if it seems interesting/useful to you.

**Comment by hkupty** [comment]
That should probably be easy to implement. I'm currently having single REPL per filetype per path.

To implement that, we can have a variable turning down the path check.

**Comment by Alok** [comment]
If that's easy, is a REPL per buffer (easily) possible?

**Comment by hkupty** [comment]
There are no real blocks here... The architectural decision was to have a repl per file type per directory. 

We can tweak that through options as long as the default behavior is still possible and all that is configurable.

**Comment by hkupty** [comment]
Closing since it didn't get any answers. Please reopen or open a new one if it's still relevant.
