### ISSUE TITLE
How to detach from the IronFocus window

### ISSUE THREAD

**Issue by sntgluca** [Vigemus/iron.nvim#356]
Dear all,

I'm walking the first steps with Iron, and enjoying it...
...until I got stuck on a simple problem...

After running some interactive commands while in focus mode, 
I am not aware of any way to detach from it, and continue writing code.

Is there a simple key combination I am not able to find?
Thank you!

**Comment by jotaefe0** [comment]
Did you tried Ctrl + "-" This should return you to Normal Mode.
Also remember you can move through windows splits using Ctrl+W and "hjkl"

**Comment by sntgluca** [comment]
Dear @jotaefe0 ,

thanks for the suggestion! 
I am afraid it didn't work.

I am not sure I explained what I am trying to do well...
As long as I use the REPL _from the neovim editor_, i.e. I send code to the REPL, everything is fine.

But if I _get into my ipython session_ to write some test code from within, I can't get out. the vim bindings don't work, as I am inside ipython at that moment.
I guess there must be a way to detach without closing the session but I can't find it...

Any other idea is still welcome :)

**Comment by raffaem** [comment]
@sntgluca does this help? https://vi.stackexchange.com/a/4922/36430

**Comment by sntgluca** [comment]
Dear all,
still no luck, at least for me...

Could you replicate the behaviour at all?

What do you do differently? Do you just use the hot-keys and never type anything interactively?

**Comment by sntgluca** [comment]
Hi all,

I learnt that I need to _exit from the terminal mode_.

A couple of discussion on the internet show that the solution is to use <C-\><C-n> - maybe map it to something of our liking.

My personal choice, after I setup the Tmux navigator, has been

`vim.keymap.set("t", "<space>F", "<C-\\><C-n>:TmuxNavigateLeft<CR>", opts)`

Hope it helps someone else
