### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by 10b14224cc** [Vigemus/iron.nvim#358]
@Vigemus is this abandoned?

Last commit was 7 months ago and issues are unreplied

**Comment by hkupty** [comment]
It's been a tough year for me personally so I couldn't really focus too much on iron (or any other of my neovim plugins). I do plan to get back at some point, but it is not easy.. Also, I've tried to get other people to help me out but that didn't work out as well. I'd love if some people would step up and offer some help.

**Comment by genaforvena** [comment]
Not anymore! :)

https://www.reddit.com/r/neovim/comments/1bsdtv1/2nd_attempt_looking_for_a_maintainer_to_help_me/ maintainers are more than welcome :)
