### ISSUE TITLE
close option gets ignored when sending one line

### ISSUE THREAD

**Issue by josecastillolema** [Vigemus/iron.nvim#366]
Hi,

first of all thanks for the amazing plugin, it is a game changer.

I use OCaml and this is my `repl_definition` setup:
```
    repl_definition = {
      ocaml = {
        close = ";;",
        command = {
          "utop",
        }
      },
    },
```

I have noticed that `;;` gets properly appended to multiline segments but unfortunately not to one line segments of code.

- In the following example the `;;` got properly auto appended
  ```
  utop # let rec sum = function
    | [] -> 0
    | h::t -> h + sum t
  ;;
  val sum : int list -> int = <fun>
  ```

- No auto append of `;;` for one liners though:
  ```
  utop # let x = 43 + 3
  ```

Am I missing something in the setup?
Thanks!

**Comment by nickeisenberg** [comment]
Hey @josecastillolema , as far as I know, there is not a `close` option of `repl_definition`. Are you using an old version of iron.nvim by any chance?

**Comment by josecastillolema** [comment]
Hi @nickeisenberg , 
I use the latest iron.nvim version, and I just confirmed the close option works and its needed.
See i.e.: https://github.com/Vigemus/iron.nvim/blob/master/lua/iron/fts/typescript.lua#L6

Btw, I couldnt get the one liners to work yet :/

Thanks

cc @hkupty any ideas?

**Comment by josecastillolema** [comment]
The workaround provided in https://github.com/Vigemus/iron.nvim/pull/376#issuecomment-2212538524 works
