### ISSUE TITLE
[bug]: send file and send until cursor in python linux doesn't works as expected

### ISSUE THREAD

**Issue by f3fora** [Vigemus/iron.nvim#369]
commit 95383e073288891fd5b609579f7daf6ad39f67eb breaks `send_file` and `send_until_cursor` in python linux.
A file like the following one, which is sent to iron, is divided in an awkward way, and the interpreter raises several errors.

It works fine if I select all the text and then `send_visual`.

```py
foo = 1


class Foo:
    def __init__(self) -> None:
        self.bar = 1

    def foo(self) -> int:
        return self.bar


bar = Foo()
print(bar.foo())
```

**Comment by f3fora** [comment]
Dear @nickeisenberg ,

I think the last approach for formatting python code of the last commits and PRs is not so solid.

I think, parsing and splitting the code, should not be done manually and by case.
I think that you can try to achieve better, more robust and general result with the appropriate tools, e.g. treesitter.

See for example #210

**Comment by nickeisenberg** [comment]
@f3fora Did send_file or send_until_cursor ever work for you? I had errors with that in the past when only `common.bracked_paste` was used. 

And I understand what you are saying about the formatting, when I have more time I will try and find better way. However, I believe I have a fix your your `send_file` and 'send_until_cursor` issue now. The latest commit should work now.

**Comment by f3fora** [comment]
> @f3fora Did send_file or send_until_cursor ever work for you? I had errors with those in the past when only `common.bracked_paste` was used.

It worked until 95383e073288891fd5b609579f7daf6ad39f67eb .

> And I understand what you are saying about the formatting, when I have more time I will try and find better way. However, I believe I have a fix your your `send_file` and `send_until_cursor` issue now. The latest commit should work now.

Thanks. It works. There is still some empty lines that are not required and fill the interpreter.

**Comment by nickeisenberg** [comment]
I just checkout out the commit prior to the one you referenced. Are you using `IPython`? `send_file` works for me on that commit for `IPython` but it fails when using `python3` as the `repl_definition`.

When I have some time, I'll see about removing that extra line that is added when sending to the terminal. Thanks!

**Comment by anku94** [comment]
Same problem, using `IPython --no-autoindent` with `python3.10` - both `send_file` and `send_until_cursor` are broken. `send_visual` and `send_line` work.

@nickeisenberg maybe try a somewhat "complicated" example? I can try figuring out a reproducible example if you are unable to reproduce.

**Comment by nickeisenberg** [comment]
@anku94 its still not working after the latest commit to master? I cant produce an example where send_file fails now.

**Comment by anku94** [comment]
@nickeisenberg sorry for the delayed response, I still seem to have issues. 

The extension now seems to separate code blocks by blank lines, and as a result, function definitions with blank lines end up getting passed as separate code blocks. Example code:

```python
def f():
  a = 5

  print(a)
```

Will produce:

```
Python 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC
 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.13.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: def f():
   ...:     a = 5
   ...: 

In [2]:     print(a)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 print(a)

NameError: name 'a' is not defined
```

This is with both `send_until_cursor` and `send_line`.

**Comment by nickeisenberg** [comment]
@anku94 this is weird, I do not have that issue

```
def f():
  a = 5

  print(a)
  
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.24.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: def f():
   ...:   a = 5
   ...:   print(a)
   ...: 

In [2]: 

```

**Comment by anku94** [comment]
Yes, that's what my config looks like. I did not have anything for python, and the new update complained about `repl_definition.python` being set to `nil`, so I added this.

**Comment by nickeisenberg** [comment]
@anku94 Can you try this

```
    local python_formatter = require("iron.fts.common").bracketed_paste_python
    iron.setup {
      config = {
        ...
        repl_definition = {
          python = {
            command = { "ipython", "--no-autoindent" },
            format = python_formatter,
          }
        }
        ...
      },
      ...
    }
```

**Comment by anku94** [comment]
This works - thank you!! :)
