### ISSUE TITLE
How to set a REPL for a filetype?

### ISSUE THREAD

**Issue by alok** [Vigemus/iron.nvim#37]
It seems like iron.nvim automatically sets up the REPL type or prompts for one. Is there a way to set your own default REPL for a filetype?

**Comment by hkupty** [comment]
There is still no persistent way to do that.
Once you run `IronPromptRepl`, iron will make use of that even after the one you were prompted for is closed.

If that doesn't suffice, I'm planning to add more customization options on the future, but there are more urgent structurings that need to be made first.

Cheers

**Comment by hkupty** [comment]
Hi,

This is now solved on the new Lua infrastructure.
