### ISSUE TITLE
iron-send-motion moves cursor to the wrong place when repeated with `.`

### ISSUE THREAD

**Issue by cmcaine** [Vigemus/iron.nvim#50]
````
search('aa*.?', 'baathomet')
search('aa*.?', 'bathomet')
search('aa*.?', 'a')
search('apple$', 'banapple')
search('^apple$', 'banapple')
````
Cursor on line 1, type `ctr_` to send the first line.

`j.` to move one line down and repeat. Line 2 is sent to REPL, but cursor moves back to line 1 (it returns to the location of the original command). `.` on any other line will also return you to line 1.

It's due to how iron_cursor_pos is updated, but I don't think it needs to be stored at all.

Pull request incoming that removes iron_cursor_pos.

**Comment by hkupty** [comment]
Thanks for helping!

Cheers!
