### ISSUE TITLE
ctr resulting in KeyError

### ISSUE THREAD

**Issue by swayson** [Vigemus/iron.nvim#54]
Not sure if I am doing this wrong or there is a bug. But every time I have text selected, i.e. in visual-mode, and I execute `ctr`. I experience the following error.

```
error caught in async handler '/home/username/.vim/plugged/iron.nvim/rplugin/python3/iron:function:IronSendMotion [['visual'], [1, 1]]'
Traceback (most recent call last):
  File "/home/username/.vim/plugged/iron.nvim/rplugin/python3/iron/__init__.py", line 144, in send_motion_to_repl
    return self.send_to_repl(["\n".join(text)])
  File "/home/username/.vim/plugged/iron.nvim/rplugin/python3/iron/__init__.py", line 166, in send_to_repl
    self.send_data(data, repl)
  File "/home/username/.vim/plugged/iron.nvim/rplugin/python3/iron/base.py", line 115, in send_data
    ft = repl['ft']
KeyError: 'ft'
Press ENTER or type command to continue
```

Any insights?

**Comment by hkupty** [comment]
Iron doesn't currently open the repl if one is not found. There was a
reason for that in the past but now it just doesn't make sense anymore.

This should be solved in the future, but for now, you can run any of the
commands that open a repl for you first (`IronRepl`, IronPromptRepl`, ...).

I'll keep this issue open while it doesn't work auto-opens the repl.

Cheers!

**Comment by hkupty** [comment]
Hi,

I'm revisiting this issue now that the lua backend is in place.

I believe things is solved now by the new implementation, so I'll close this issue but feel free to reopen if it persists or open a new one have you had any other issue or question.

Cheers,
Henry John Kupty
