### ISSUE TITLE
Multiline ipython not working in linux - needs an additional '\n'

### ISSUE THREAD

**Issue by svenski** [Vigemus/iron.nvim#64]
When I select multiple lines and sent to the IPython REPL it waits for more input before it evaluates. I can make it evaluate by either switching to the REPL and add a CR or send an empty line. 

I fixed it locally by adding an additional `\n` to the python specific repl: `'multiline': ('\x1b[200~', '\x1b[201~', '\r\n'),` , I was going to make a pull request but I don't know if that breaks things for others. Let me know if you like me to do it. I _think_ `\r` only works on OSX.  I'm not entirely sure how it's evaluated, an os specific `os.linesep` might be better if it's evaluated in python. 

Thanks for plugin!

**Comment by hkupty** [comment]
Hi! Thanks for sending the issue. That makes complete sense.
while `\r` has worked for me in linux as well, this is somewhat complex as might be related to system locale, terminal configuration and other stuff (I'm guessing). Nonetheless, python is much better at attempting the correct value than a hardcoded one. I'll update asap - probably for every language that has multiline capabilities. It seems like a sane default.

Cheers!

**Comment by Alok** [comment]
Wrapping in bracketed paste escape sequences  may fix all the pasting issues: https://github.com/christoomey/vim-tmux-runner/pull/81

**Comment by hkupty** [comment]
Hi,

Now that the lua backend is in place, I believe that this was implemented correctly in the first place, so this issue should be solved by now.

Could you double check?

Cheers,
Henry John Kupty

**Comment by hkupty** [comment]
Closing since it didn't get any answers. Please reopen or open a new one if it's still relevant.
