### ISSUE TITLE
Error on first usage of :IronRepl

### ISSUE THREAD

**Issue by rTreutlein** [Vigemus/iron.nvim#68]
The first time i run :IronRepl i get the folloing error. After that it seems to work. I also can't seem to send any text to the repl "ctr$" just does nothing.

Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:
line    2:
error caught in request handler '/home/roman/.config/nvim/plugged/iron.nvim/rplugin/python3/iron:command:IronRepl [0]':
Traceback (most recent call last):
  File "/home/roman/.config/nvim/plugged/iron.nvim/rplugin/python3/iron/__init__.py", line 70, in create_repl
    self.iron_repl([ft], bang=bang)
  File "/home/roman/.config/nvim/plugged/iron.nvim/rplugin/python3/iron/__init__.py", line 101, in iron_repl
    self.open_repl(template, **kwargs)
  File "/home/roman/.config/nvim/plugged/iron.nvim/rplugin/python3/iron/base.py", line 311, in open_repl
    create_new_repl()
  File "/home/roman/.config/nvim/plugged/iron.nvim/rplugin/python3/iron/base.py", line 300, in create_new_repl
    repl_id = self.termopen(command, with_placement)
  File "/home/roman/.config/nvim/plugged/iron.nvim/rplugin/python3/iron/base.py", line 93, in termopen
    return open_term(self.nvim, cmd)
  File "/home/roman/.config/nvim/plugged/iron.nvim/rplugin/python3/iron/zen/ui.py", line 81, in open_term
    ret = nvim.funcs.termopen(cmd)
  File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 229, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 130, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 97, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim:Can only call this function in an unmodified buffer'
Error detected while processing function remote#define#CommandBootstrap:
line    5:
E171: Missing :endif

**Comment by hkupty** [comment]
This is strange.

Could you paste the versions of neovim and the neovim python lib you're using?

**Comment by rTreutlein** [comment]
I am on Arch Linux and using the community repo to install NeoVim which is version 0.2.2 atm and the python lib is version 0.2.0

**Comment by hkupty** [comment]
I just tested here and everything seems to be working correctly.. Can you give more details regarding repl type and what happens besides the stack trace? Any information will help debugging this..

Cheers,

**Comment by rTreutlein** [comment]
Well I open nvim then open a .py file via NerdTree then either IronRepl or IronPromptRepl (no difference) causes the error while also opening an empty split. Then running the command again another split opens with the repl active inside.
But even with it open I can't send any text to the repl unless I enter it manually ("ctr$" does nothing, well the "ctr" does change the cursor and with "$" it changes back but nothing happens.)

Hope that helps. Ill be trying this on another system of mine and see how it goese there.

**Comment by nothingaboutdata** [comment]
I have the same issue. error occur when i initial IronRepl, but it still work after the error. 
I can only access these commands
`
IronClearReplDefinition 
IronDumpReplDefinition
IronPromptCommand
IronPromptRepl           
IronRepl
`
and these commands are missing:
`
IronSend
IronSendMotion
IronSendSpecial
`
my python version is 3.6.3 with GCC 7.2.0, 
neovim python lib 0.20,  
NVIM v0.2.3 ,
Lua 5.1.4,
Red Hat 4.4.4-13

**Comment by hkupty** [comment]
Ok, I could get what's happening but not why. It's trying to open a new repl over the current buffer instead of opening the repl over a new buffer, created with `enew`. Since the current buffer is modified (but not saved), the repl opening fails. This is very strange.

**Comment by hkupty** [comment]
Hi,

I'm revisiting this now that iron has changed to a lua backend. 

This issue should be gone, since there's no python/pynvim/remote abstraction layer in between. 

I'll close this but feel free to reopen if you're using the legacy python backend or open a new one if you have any other questions or problems. 

Cheers, 
Henry John Kupty
