### ISSUE TITLE
Clojure set ns to current file doesn't work with buffers in /tmp/

### ISSUE THREAD

**Issue by philomates** [Vigemus/iron.nvim#69]
If I'm in a clojure project and I use `acid.nvim` to go to the definition of a library's function it will open that function's file in a temporary directory like `/tmp/random-id/the-lib/misc.clj`

When using `iron.nvim`'s `<leader>sn` to make the repl's namespace match that `/tmp/random-id...` buffer's namespace I get `(in-ns misc)` instead of  the expected `(in-ns the-lib.misc)`

Fixing this will allow one to more easily change the definition of a lib's function during exploratory development; something that is possible in emacs development flows

**Comment by hkupty** [comment]
Unfortunately, the problem might be on acid instead, since, when acid is present, iron delegates the task:
https://github.com/BurningEther/iron.nvim/blob/master/rplugin/python3/iron/repls/clojure/utils.py#L9.

I'll make sure the problem indeed not here, but I'd bet its not.

Cheers
