### ISSUE TITLE
scroll terminal after IronSend

### ISSUE THREAD

**Issue by benkj** [Vigemus/iron.nvim#73]
I use the REPL actively from the text editor and I made some custom bindings to IronSend to send text from the editor and watch the output on the REPL. The problem is that for a long output the terminal never scrolls down, so after a few IronSends, my output is already hidden. Is it possible to scroll the terminal down after each IronSend?

**Comment by hkupty** [comment]
First of all, thanks for the issue.

I'm not sure. I've already tried scrolling non-active windows in the past and it was not possile at the time. We can check that through the neovim gitter and, if it is a limitation on their side, I'll open up an issue for them linking to this one.

Cheers,
Henry

**Comment by yelled1** [comment]
Actually, neoterm does implement this behavior. Hoping very much to get this working.

**Comment by yelled1** [comment]
@benkj  Do u mind sharing custom binding? Trying to make 
make below work / just like Atom: <C-CR> does not work on some terminals

"inoremap <silent> <C-CR> <C-O>:TREPLSendLine<CR>
"nnoremap <silent> <C-CR> :TREPLSendLine<CR>j0
"vnoremap <silent> <C-CR> $:TREPLSendSelection<CR>'>j

"inoremap <silent> <NL> <C-O>:TREPLSendLine<CR>
"nnoremap <silent> <NL> :TREPLSendLine<CR>j0
"vnoremap <silent> <NL> $:TREPLSendSelection<CR>'>j

**Comment by benkj** [comment]
Sure, my bindings are quite simple . I use IronSend mostly with julia, so here are my bindings

```
autocmd Filetype julia  nmap §§ :write<CR>:call IronSend("include(\"" . expand("%:p") . "\")")<CR>
autocmd Filetype julia  nmap ,lf :call IronSend("include(\"" . expand("%:p") . "\")")<CR>
autocmd Filetype julia  nmap ,lr :IronRepl<CR>
autocmd Filetype julia  vmap <buffer> ,t <Plug>(iron-send-motion)
autocmd Filetype julia  nmap <buffer> ,t <Plug>(iron-send-motion)
autocmd FileType julia nmap ,w  :call IronSend("@doc " . expand("<C-R><C-W>"))<CR>G<CR>
```

The easiest way to reproduce my problem is to create a julia file, foo.jl, write a command (e.g. "eye") on that file, and then press ,lr to open the REPL and ,w on top of that command to look for the documentation.  You will see that the terminal doesn't scroll down (although for doc this could be good)

**Comment by yelled1** [comment]
This is what I end up doing
which gets rid of two annoyance:
1) after visual exec scroll to end of selection
2) Do NOT scroll to the end after execution to Repl

```autocmd FileType python map <silent> <leader>, <Esc>`>a<ESC><C-w>jG<C-w>pj0```
since my leader key is ```,``` = I just hit ```,,``` quickly after

**Comment by lucc** [comment]
I assume there is some feature in the terminal of neovim that can do that (follow the output). If I open a terminal and run a command like this:
```
while sleep .3; do echo $((i++)); done
```
And then I leave terminal mode and move to another window the terminal follows the output.

So there should be some solution without adding code to the actual `IronSend` implementation or the user just has to take care that the terminal/repl is at the end of the output *before* `IronSend`ing stuff.

**Comment by hkupty** [comment]
Sorry for not answering before.

I'm investigating it (though this week I'm barely touching my computer).

It seems neovim should follow the scroll if the cursor is in the last line.

I'll dig further and update this.

Cheers,
Henry John Kupty

**Comment by randomizedthinking** [comment]
I noticed the same issue when using iron... Just as @hkupty said, the terminal buffer will scroll if the cursor is at the last line. Wonder what configuration would fix this issue...

**Comment by hkupty** [comment]
Not sure if there's anything to do on this one. I'll close the issue, feel free to reopen or open a new one if it's actionable.

Best regards,
Henry
