### ISSUE TITLE
<Plug>(iron-send-motion) changes the < and > marks

### ISSUE THREAD

**Issue by urbainvaes** [Vigemus/iron.nvim#74]
This produces unexpected results when trying to use `gv`.

**Comment by hkupty** [comment]
I think this is a pretty normal behavior for plugins that work over text objects. I don't do anything special on this case to set up `<` and `>`, as you can see [here](https://github.com/BurningEther/iron.nvim/blob/da98657f1d8b0ac24854df97d1470e9a3450a881/plugin/iron.vim#L1-L2).

**Comment by urbainvaes** [comment]
Thanks for the response!

Are you sure? because I think that this issue does not appear in
some other plugins that also work with text objects...

Also, in my `.vimrc` I have a function like this,

```vim
function! FillSearch(...)
    if a:0 == 0
        let l:filltext = ""
    else
        let l:is_visual=(a:1 == "v")
        let l:line=getline(l:is_visual ? "'<" : "'[")
        let [line1,col1] = getpos(l:is_visual ? "'<" : "'[")[1:2]
        let [line2,col2] = getpos(l:is_visual ? "'>" : "']")[1:2]
        let l:filltext =l:line[col1 - 1: col2 - 1]
    endif
    call feedkeys(':grep' . ' "' . l:filltext . '"'."\<Left>")
endfunction

nnoremap <silent> g/  :set opfunc=FillSearch<cr>g@
```

and it does not change the `<` and `>` marks either,
when called from normal mode.

Best wishes,

Urbain

**Comment by urbainvaes** [comment]
Related to this, I have noticed that `<Plug>(iron-send-motion)` messes with folds sometimes, for example when doing `yrgg` when there are folds above the current position. (`yr` being my binding to `iron-send-motion`). It seems that the plugin moves the cursor at some point, no? Is this necessary?

Also, I wanted to say that I really like this plugin - thank you for the good work! :)

**Comment by hkupty** [comment]
>  because I think that this issue does not appear in some other plugins that also work with text objects... 

Yeah, you got me thinking on this.. I'll do some tests, but if it's not related to opfunc than it should either be `<c-u>` or `winsaveview()`s fault.

On python side, nothing seems to cause such change on the marks.

As for the folds. I'd bet that those are related to `winsaveview()`.

I'll test those now and will post my findings afterwards.

> Also, I wanted to say that I really like this plugin - thank you for the good work! :)

Thank you very much! I'm really glad that you enjoy the plugin.

Cheers,
Henry John Kupty

**Comment by hkupty** [comment]
Hum.. None seem to be involved. My last guess - by exclusion - is that this has to do with how the remote client handles ranges and so on. If this is the case, this will be solved by migrating to lua - which I'll retake in the upcoming weeks.

**Comment by urbainvaes** [comment]
> Yeah, you got me thinking on this.. I'll do some tests, but if it's
> not related to opfunc than it should either be `<c-u>` or
> `winsaveview()`s fault.
>
> On python side, nothing seems to cause such change on the marks.
Yeah, I had a look at the code, and I don't see where the side-effects
might be coming from either...

> As for the folds. I'd bet that those are related to `winsaveview()`.
>
> I'll test those now and will post my findings afterwards.
Thanks! I'll let you know too if I find something.

**Comment by hkupty** [comment]
Hi,

I'm just wondering if this is fixed after the migration to lua backend or if it still persists.

Could you help me with that? 

Cheers,
Henry John Kupty

**Comment by hkupty** [comment]
Hi,

I hope you have tested the (not so) new version by now :sweat_smile:.

Do you think we can close this one?

Best regards,
Henry

**Comment by urbainvaes** [comment]
Hi Henry,

I had been using the legacy branch, but I'll switch to the master branch now. :) I'll let you know and reopen the issue if I see any of the bugs I reported before.

Best wishes,
Urbain
