### ISSUE TITLE
Connect to remote REPL

### ISSUE THREAD

**Issue by rzpilgrim** [Vigemus/iron.nvim#84]
It would be great if this plugin could be configured to connect to a remote REPL (via ssh, for instance).

**Comment by hkupty** [comment]
Nice Suggestion.

To be honest, it depends more on the client than on iron, since this merely invokes the client process.

*Connecting* to an existing REPL would need to be supported by the underlying REPL client. It is, for example, pretty simple to do that with `lein` for clojure: `lein repl :connect host:port`.

What iron could provide is a nicer interface for exposing such options depending on the language/REPL.

Do you have any language in mind where that is an issue?

Cheers,
Henry

**Comment by rzpilgrim** [comment]
I'm currently working on a remote Python project. What I'd like to do is connect to an IPython kernel that is running on a server, while editing and sending text locally (with syncing handled by rsync).

I know you can do this using `jupyter console`, but it would be great if there were some configuration options exposed in vimscript for a `.rc` file. You could, for example, specify the host in `ex` mode or in your `.rc`, launch a process that `ssh`es in to the host, starts a REPL, exits, and connects the current neovim session.

**Comment by hkupty** [comment]
I'll do some testing for that before. It definitely would be great to have REPL-over-SSH out of the box with iron.

it can still be done today - specially if you use the new lua-based implementation, you could add right now a definition of it on your config like this:

```vim
lua << EOF
local iron = require("iron")

iron.core.add_repl_definitions{
  python = {
    over_ssh = {
      command = "ssh $TGT ipython",
      type = "bracketed"
    }
  }
}

iron.core.set_config{
  preferred = {
    python = "over_ssh"
  }
}
EOF
```

So, if you're using the new lua-based interface, that'd be a great test for it's new capabilities.

Obviously, adding facilities for that would greatly benefit usage as you wouldn't need to specify a `$TGT` env var.

WDYT?

**Comment by rzpilgrim** [comment]
I haven't ever programmed in lua, so I'm not sure exactly where I'm supposed to be putting this code, or the code on the homepage. I'd like to try though, so let me know and I'll give it a shot.

**Comment by hkupty** [comment]
You can just paste this snippet into your `init.vim`.

To use Iron with the lua api, as I didn't replace (yet) the commands to use the lua version, you can run `:lua require("iron").core.repl_for("python")`.

**Comment by rzpilgrim** [comment]
Does this assume that I've already installed the `iron` package for lua?

All that did was open a local `python` (not `ipython`) session.

**Comment by hkupty** [comment]
I'm assuming you're using a somewhat recent version of neovim (0.2.3 or 0.3).

Lua capabilities are embedded into neovim for some time now, so if you are using a recent version you already have lua.

**Comment by rzpilgrim** [comment]
I have neovim 0.3.0.

I've inserted that code into my init.vim, but nothing is changing. Is there some config I need to do to enable the Lua backend instead of Python?

**Comment by hkupty** [comment]
Run this (`:lua require("iron").core.repl_for("python")`) instead of `:IronRepl`. This way you open the repl the lua backend, instead of the Python one.

**Comment by hkupty** [comment]
I'll change the commands to use the lua backend this week, so (hopefully) it'll be transparent.

**Comment by rzpilgrim** [comment]
I tried running the command. It only opened an empty, unnamed buffer.

**Comment by rzpilgrim** [comment]
Not sure why it wasn't working before, but the REPL opened this time. I tried sending text using the old maps, but that didn't work. I suppose I shouldn't expect them to work with the new backend.

Thanks for all your work on this plugin!

**Comment by hkupty** [comment]
Glad to know that it worked this time. I'm currently replacing the mappings and commands (the interface so to speak) so they can use the new backend.

I expect that in the next few days you'll be able to use it natively as you would with the Python backend.

I'm honestly happy that you enjoy my work with iron! Thanks for the feedback and the issue, so I can make it even better!

**Comment by rzpilgrim** [comment]
No problem!

I have an unrelated question: is it possible to send the REPL to a tmux session? I am using macOS, and iTerm2 allows the display of images in the terminal. I can get inline plots in a regular terminal session, but in neovim it breaks.

If I could send to a tmux session or even another bash instance, then my interactive dev environment would be super productive.

**Comment by rzpilgrim** [comment]
You're welcome. This plugin was sorely needed and it helps me be more productive by allowing really tight REPL integration.

I'm working in macOS, and I can get plots in the terminal with iTerm2, but in neovim, this functionality breaks. As an unrelated question, do you have any idea whether there's a way to mirror the execution of an ipython session? If I could mirror in a tmux or iTerm pane, then I would have the dream dev environment (X11 is waaayyyy too slow).

**Comment by hkupty** [comment]
Hi,

I'm thinking that this issue might have been solved by now.

I'll close it, but feel free to reopen if it persists or open a new one have you had any other issue or question.

**Comment by dkioroglou** [comment]
I'm reopening the issue because the above implementation does not work in my case.

**Neovim specifications**
```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794
```

**Code** 
included in `ironvim.lua`
```
local iron = require("iron")

iron.core.add_repl_definitions{
  python = {
    over_ssh = {
      command = "ssh -p NUM username@serverip ipython",
      type = "bracketed"
    }
  }
}

iron.core.set_config{
  preferred = {
    python = "over_ssh"
  }
}
```
**Error**
When I run:
```
:lua require("iron").core.repl_for("python")
```
I get the error
```
Failed to run `config` for iron.nvim
.../plugins/configs/ironvim.lua:67: attempt to call field 'add_repl_definitions' (a nil value)
# stacktrace:
  - ~/.config/nvim/lua/plugins/configs/ironvim.lua:67
  - ~/.config/nvim/lua/plugins/init.lua:11 _in_ **config**
  - lua:1 
```
