### ISSUE TITLE
Split is always vertical on windows

### ISSUE THREAD

**Issue by hkupty** [Vigemus/iron.nvim#91]
As mentioned on [#89 (comment)](https://github.com/Vigemus/iron.nvim/issues/89#issuecomment-430535558l).

I'll investigate and post my findings here.

Ping: @benignoc, @r-tanner-f.

**Comment by alexhbnr** [comment]
Is there any update on this?
I very much prefer the splits horizontal, too, but cannot get it to work either.

**Comment by hkupty** [comment]
I couldn't find anything specific yet, but it's difficult since I don't have a windows machine to test on, so all my assumptions are hypothetical.

Just for reference, the command should be something like this:

```viml
:lua require("iron").core.set_config{repl_open_cmd = "rightbelow 10 split"}
```

If you run that, do you get any error/message?

**Comment by hkupty** [comment]
When I run that on linux, it works correctly, so unless there's a bug on windows' version of neovim, I'm not really sure how to even test that.

@benigno & @r-tanner-f, could you add some debug information as well?

**Comment by alexhbnr** [comment]
I don't have a Windows system either, but Mac OS X.

If I run the command that you stated

`:lua require("iron").core.set_config{repl_open_cmd = "rightbelow 10 split"}`

I don't get any error message. Running `:IronRepl`, then correctly splits the window horizontally. 
However, if I don't run the lua command first but just start with `:IronRepl`, I always get a vertical split. 

Is there a way to run the lua command at the start of neovim but putting something in the init.vim?

**Comment by yelled1** [comment]
Perfect this works:
lua require("iron").core.set_config{repl_open_cmd = 'rightbelow 10 split'}
or
lua require("iron").core.set_config{repl_open_cmd = 'topleft vertical 80 split'}

**Comment by ohspc89** [comment]
Hi. I have read this issue and have added the line
**lua require("iron").core.set_config{repl_open_cmd = 'rightbelow 10 split'}**
to init.vim. I am currently working on an Ubuntu 18.04 machine.

Before adding that line, :IronRepl command opened Ipython as I have set. Now, after adding that line, the same command opens python 2.7. Does this have something to do with PATH?

Sorry, I am a relative newbie, so any feedback is much appreciated.

**Comment by hkupty** [comment]
I'm pretty sure the issue is unrelated. Nonetheless, to have ipython as default, you can replace that line with this snippet to make sure you'll always pick ipython:
```lua
lua << EOF
require("iron").core.set_config {
    repl_open_cmd = 'rightbelow 10 split',
    preferred = {
        python = "ipython"
    }
}
EOF
```

**Comment by ohspc89** [comment]
Worked like a charm. Thanks!

**Comment by hkupty** [comment]
@ohspc89 Glad I could help! :smile:
