### ISSUE TITLE
IronREPL does not seem to have a normal mode

### ISSUE THREAD

**Issue by derekbrokeit** [Vigemus/iron.nvim#93]
Thank you for this very exciting plugin for nvim. Perhaps I misunderstand the functionality, but everytime I run `:IronRepl` I am entered into the repl with no escape except to exit the repl. The escape key appears to be sent to the other side. I tested this using both standard python repl and ipython. If I attempt to change buffers (e.g. `<C-W>j`) I do not see a buffer change. I have to exit the repl. I get the impression that this should be standard functionality. I am at a loss as to solving the problem. It would be great to be able to copy text from the REPL or move to a file buffer and be able to send selected text. I attempted to disable everything in my vimrc except the installation of iron through Vundle with no luck. Thanks in advance for any advice in better understanding the usage of iron.nvim.

**Comment by hkupty** [comment]
Hi,

Thanks for using Iron and for the interest. This seems to be a common shortcoming so I better write some docs about it.

Iron uses default neovim's `terminal`, which means the mechanisms for getting in/out of `Terminal Mode` are handled by neovim and it's mappings.

By default, you need to use `<C-\><C-N>`. Please refer to `:h terminal-input` for more on neovim terminal.

Please, don't refrain from opening new issues if you still have problems either with this or something else.

Cheers,
Henry

**Comment by derekbrokeit** [comment]
Thanks! That's exactly what I needed. I had not realized this, I am very new to neovim. This would certainly be useful in the documentation.

**Comment by hkupty** [comment]
Awesome! Glad to hear that.

I'll keep this issue open until I add that to the docs.

Cheers,
Henry

**Comment by nequals30** [comment]
I'm also very new to neovim and had trouble figuring this out. I'm glad someone asked this recently!

**Comment by hkupty** [comment]
The new documentation is on the way. Hopefully it'll solve most of the common pitfalls.
