### ISSUE TITLE
how to replace IronPromtComman for working with virtual environments?

### ISSUE THREAD

**Issue by mamueller** [Vigemus/iron.nvim#94]
Hi, I am really thankful for the iron package since it allows me to work with ipython,R and the shell at the same time.
When working in python I usually work in virtual environments. 
Up to now I did this by issuing an
 
IronPromtCommand 
and then write something like :"source my_virtual_env/bin/activate ; ipython"
This also worked with the Django database shell:
 IronPromtCommand
""source my_virtual_env/bin/activate ; path/to/djangos/mysite/dir/manage.py shell"

I do not know how to accomplish these tasks now.
I think it should be really easy to create customized repls for these cases with a small lua file like with iron.core.add_repl_definitions{....
Is this the way to go?
A concrete example in the Readme would really help.

Thanks in advance

**Comment by mamueller** [comment]
Many thanks for the quick answer!
Markus

Am Fr., 16. Nov. 2018 um 16:24 Uhr schrieb Henry John Kupty <
notifications@github.com>:

**Comment by hkupty** [comment]
No worries. I did however point you to the wrong sample in the link there. [This is the correct one](https://github.com/Vigemus/impromptu.nvim/blob/master/docs/sample.md) as it creates a menu to select the repl definitions.

**Comment by mamueller** [comment]
Thanks.
I finally got to work the original approach with the full path to my ipython in the virtual env.
I also had some trouble to figure out the actual line that goes into my init.vim (originally I thought the run and the backticks in the iron docs where necessary...)
I still do not know how to  use the linked impromtu example although I have a rough idea what it is supposed to do.
I think a minimal but complete working example would be a good option for the documentation .  
I think most programmers could take it from there.  
(I have never seen lua code before and also never written vim plugins, so I do not know how to use this infrastructure (which is obviously obvious for you ;-).
I was actually a bit scared to get lost in the attempt to make it work. It could probably change a simple example though...)

another comment:
It is good that one does not have to start vim with the virtual env already sourced since this interferes with other packages (for me especially with the YouCompleteMe plugin)
From the little, I understand the new design looks very clean and modular. 
Thank you very much for sharing.

**Comment by hkupty** [comment]
Wonderful!

I'm glad you could make it work!

Also, I understand the need for better documentation and I will do something similar to what I did with [impromptu.nvim](https://impromptunvim.readthedocs.io/en/latest/).

Hopefully that'd be better for iron.nvim, as it's actually becoming more of a library than simply a plugin.

I'll make sure to add the venv bits there.

Thanks for the up vote on the new architecture. It's still evolving but surely it has shown a greater potential compared to the old python version.

**Comment by hkupty** [comment]
I'll close this issue, but feel free to reopen it or open a new one if you have any other issues or questions.

Cheers,
Henry John Kupty
