### ISSUE TITLE
Viml function alternative to motion-based API

### ISSUE THREAD

**Issue by fennerm** [Vigemus/iron.nvim#95]
It would be really nice if iron.nvim exposed a Vimscript function which allowed users to send arbitrary text to the REPL as an alternative to the current API which uses motions.

E.g usage
```
call SendTextToRepl("x=6+6")
```
This would make simple scripting with Iron a lot simpler.

**Comment by hkupty** [comment]
Hi,

Thanks for the issue and the interest in making iron better.

It doesn't provide a VimL function, but it does provide a lua function that does that.

One could do the following instead:

```vim
lua require("iron").core.send("python", "x=6+6")
```

Or, if you don't want to mess with lua, a convenience command exists for that:

```vim
IronSend python x=6+6

" The command can take any number of args, it'll join them as a line 
IronSend python x = 6 + 6

"the bang version takes the current &ft
IronSend! x = 6 + 6
```

But note that I'm still uncertain about maintaing a VimL API, so it can change in the future.

I still need to document this better though, so I'll keep your issue open for reminding me of that, but please don't refrain to extend your question or ask for more information in this or other issue.

Cheers,
Henry

**Comment by fennerm** [comment]
I had a feeling I was missing something, thanks!

**Comment by hkupty** [comment]
By the way, if you consider scripting on top of Iron, take a look at the init.lua file, specially the functions defined under `iron.core`. Also, check [trex.nvim](https://github.com/Vigemus/trex.nvim)  for an example of extensions over iron.nvim.

Cheers

**Comment by hkupty** [comment]
I'll consider this done, but don't refrain from opening another issue if you have any further questions or comments.

Cheers,
Henry John Kupty
