### ISSUE TITLE
iPython REPL not working

### ISSUE THREAD

**Issue by pdoak** [Vigemus/iron.nvim#96]
I have installed `iron.vim` and when I send a line of python code it opens a terminal window and I get:
```
Python 2.7.10 (default, Aug 17 2018, 17:41:52)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
```
Whereas, I would like it to launch `iPython` . The version I am running is iPython 7.1.1. Can `iron.vim` do this?

**Comment by hkupty** [comment]
Hi, thanks for the issue. I'm working on improving the API for simplifying the choice of the preferred repl for each specific use case.

Right now, the way to do that is by configuring iron:

```viml

lua require("iron").core.set_config{
  preferred = { python = "ipython"}
}
```

That can change in the future, but ideally this is the concept behind it.

I'm working on something that could provide on-the-fly selection, for example. If you are interested, take a look at [impromptu.nvim](github.com/Vigemus/impromptu.nvim).

You can tinker around its API and irons to build something smarter. That's my end goal when impromptu becomes stable.

Cheers,
Henry John Kupty

**Comment by pdoak** [comment]
Thanks for the reply, Henry. I don't understand what I need to do with the code you suggested. Please, could you give me some more details on how to implement the configuration?

Many Thanks

Paul

**Comment by hkupty** [comment]
Sure.

Iron is now configured in lua, so you have to use lua through VimL.

You can add that snippet in your `init.vim`.

Another approach would be to have a lua configuration file in your config directory and reference it on your `init.vim` through `luafile` viml command.

You can check my [dotfiles](github.com/hkupty/dotfiles) for reference.

Feel free to ping me again if you still need help.

Cheers,
Henry John Kupty

**Comment by pdoak** [comment]
The link to you dotfiles does not work.

When I put the code snippet into my `init.vim` I get these errors:

```
Error detected while processing /Users/xxx/Developer/PDSetup/roles/dotfiles/files/nvim/settings_new/mappings.vim:
line  214:
E5104: Error while creating lua chunk: [string "<VimL compiled string>"]:1: unexpected symbol near '<eof>'
line  215:
E492: Not an editor command:   preferred = { python = "ipython"}
line  216:
E492: Not an editor command:   }
4 fewer lines
/Users/xxx/Developer/PDSetup/roles/dotfiles/files/nvim/settings_new/mappings.vim:
line  214:
E5104: Error while creating lua chunk: [string "<VimL compiled string>"]:1: unexpected symbol near '<eof>'
line  215:
E492: Not an editor command:   preferred = { python = "ipython"}
line  216:
E492: Not an editor command:   }
Error detected while processing /Users/xxx/Developer/PDSetup/roles/dotfiles/files/nvim/settings_new/mappings.vim:
line  214:
E5104: Error while creating lua chunk: [string "<VimL compiled string>"]:1: unexpected symbol near '<eof>'
line  215:
E492: Not an editor command:   preferred = { python = "ipython"}
line  216:
E492: Not an editor command:   }
```

**Comment by hkupty** [comment]
Sorry, I mistyped the snippet.

You should have a space before EOF:
```viml
lua << EOF
...
```

**Comment by pdoak** [comment]
Thanks. That worked.

**Comment by hkupty** [comment]
I'm glad it worked!

Please don't refrain from opening another issue if you have any more questions.

Cheers,
Henry John Kupty
