### ISSUE TITLE
How to create a repl for a new filetype with the new API?

### ISSUE THREAD

**Issue by icyd** [Vigemus/iron.nvim#97]
I have a filetype **pandoc** and I want to add a python's repl to that filetype. I've going through the files, but don't have enough knowledge of lua to make that. As I understand the documentation is a work in progress.

**Comment by hkupty** [comment]
Hi, thanks for your issue.

To create a new repl definition, you have to add it through the lua API as follows:

```vim
lua << EOF
local iron = require("iron")

iron.core.add_repl_definitions{
  pandoc = { -- This should be the file type
    pandoc_repl = {
      command = "python" -- This should be the command you want to run.
    }
  }
}

-- Optionally, if you have more than one definition for the `pandoc` filetype, you can:
iron.core.set_config{
  preferred = {
    pandoc = "pandoc_repl"
  }
}

EOF
```

Hopefully that solves your issue. I've been focusing on [impromptu.nvim](https://github.com/Vigemus/impromptu.nvim) as it will allow much a smoother configuration and selection of definitions and configurations. Take a look at that if you're interested in something more dynamic.

Cheers,
Henry John Kupty

**Comment by hkupty** [comment]
Also, note that if you're running a compound command for the component, eventually neovim prefers to receive the arguments as separate strings instead of a single string. To do that, you can try defining the command as follows:

```lua
-- local iron ...

iron.core.add_repl_definitions{
  pandoc = { -- This should be the file type
    pandoc_repl = {
      command = {"python", "-m", "my.module"}
    }
  }
}

```

**Comment by icyd** [comment]
Thank you for your fast reply, the solution works great. Also thanks for your amazing work. As I was looking  for solutions through the issues, I read the one asking for Repl for python with virtualenv. I don't know if can help you, but I can give you some insight how I'd make it work. If you use pyenv in conjuntion with .python-version, when you open that directory the correct _pyenv_ will be activated. So if you put that together with a pluggin like [Vim-Rooter](https://github.com/airblade/vim-rooter), it will automatically change the directory to the project root, therefore when **IronRepl** is executed the correct version of _python_ will be used. Hope that helps.

**Comment by hkupty** [comment]
I'm really glad it worked and grateful that you like iron.nvim.

As for the venv, it should be simple if you point directly to the Python executable inside the venv folder.

I'll eventually start writing plugins that extend iron.nvim, with things such as detecting and adding venv repl definitions.

Feel free to ping me if you have any further questions or ideas for iron.nvim. I'll close this issue but if something else is missing you can reopen it at any time. 

Cheers,
Henry John Kupty
